backend:
  - changed-files:
      - any-glob-to-any-file: "backend/**"

frontend:
  - changed-files:
      - any-glob-to-any-file: "frontend/**"

ci:
  - changed-files:
      - any-glob-to-any-file: ".github/**"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "docs/**"

docker:
  - changed-files:
      - any-glob-to-any-file:
          - "Dockerfile"
          - "docker-compose.yml"
